### ISSUE TITLE
Change names of fields in return type of sim_phenotype 

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tstrait#106]
I think it would be clearer if we had

```
result = sim_phenotype()
result.traits  #  output of sim_trait
result.phenotypes # output of sim_phenotype
```
assuming that we do the refactoring in #103

**Comment by daikitag** [comment]
I totally agree with https://github.com/tskit-dev/tstrait/issues/103, but I'm actually thinking about changing the name of `sim_trait` function to `sim_effect_size`. Trait and phenotype are usually used interchangeably. Instead of confusing the user through these terms, I think we should name them as `effect_size` and `phenotype`, so that it is very clear to understand.

**Comment by jeromekelleher** [comment]
An effect size is for a single causal site though, right? A trait gets across the idea of having multiple causal sites (and consequently multiple effect sizes) better I think

**Comment by daikitag** [comment]
Issue resolved in https://github.com/tskit-dev/tstrait/pull/112
